# Specify the day for weekly checks

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays at 9am UTC
      day: "sunday"
      time: "09:00"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
